In [34]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn. feature_selection import SelectKBest
from sklearn.feature_selection import chi2

filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','class']

dataframe = read_csv(filename, names=names)
array = dataframe.values
x=array[:,0:7]
y=array[:,7]
test=SelectKBest(score_func=chi2,k=5)
fit=test.fit(x,y)
#set_printoptions(precision=4)
print(fit.scores_)
features=fit.transform(x)

[1411.887    17.6054   53.108  2175.5653  127.6693    5.3927  181.3037]


In [32]:
x=fit.scores_
x

array([1411.887 ,   17.6054,   53.108 , 2175.5653,  127.6693,    5.3927,
        181.3037])

**Recursive Feature Elimination**

In [29]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','class']

dataframe = read_csv(filename, names=names)
array = dataframe.values
x=array[:,0:7]
y=array[:,7]
model=LogisticRegression(max_iter=400)
rfe=RFE(model)
fit=rfe.fit(x,y)

In [30]:
fit.support_

array([ True, False, False, False,  True,  True, False])

In [24]:
fit.ranking_

array([2, 3, 4, 5, 1, 1, 1, 1])

**Decision Tree**

In [28]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
x=array[:,0:7]
y=array[:,7]
model=DecisionTreeClassifier()
model.fit(x,y)
print(model.feature_importances_)

[0.3155 0.1169 0.0543 0.0282 0.2191 0.1286 0.1373]
