<a href="https://colab.research.google.com/github/lavanya5454/lavanyagit/blob/main/Featured_engineering%20and%20model%20validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn. feature_selection import SelectKBest
from sklearn.feature_selection import chi2

filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','class']

dataframe = read_csv(filename, names=names)
array = dataframe.values
x=array[:,0:7]
y=array[:,7]
test=SelectKBest(score_func=chi2,k=5)
fit=test.fit(x,y)
#set_printoptions(precision=4)
print(fit.scores_)
features=fit.transform(x)

[1411.88704064   17.60537322   53.10803984 2175.56527292  127.66934333
    5.39268155  181.30368904]


In [31]:
x=fit.scores_
x

array([1411.88704064,   17.60537322,   53.10803984, 2175.56527292,
        127.66934333,    5.39268155,  181.30368904])

**Recursive Feature Elimination**

In [32]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','class']

dataframe = read_csv(filename, names=names)
array = dataframe.values
x=array[:,0:7]
y=array[:,7]
model=LogisticRegression(max_iter=400)
rfe=RFE(model)
fit=rfe.fit(x,y)

In [33]:
fit.support_

array([ True, False, False, False,  True,  True, False])

In [34]:
fit.ranking_

array([1, 3, 5, 4, 1, 1, 2])

**Decision Tree**

In [35]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
x=array[:,0:7]
y=array[:,7]
model=DecisionTreeClassifier()
model.fit(x,y)
print(model.feature_importances_)

[0.31323702 0.11091331 0.05771393 0.04736705 0.21323377 0.12970855
 0.12782638]


In [36]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
dataframe
x=dataframe.iloc[:,0:7]
y=dataframe.iloc[:,7]
model=SelectKBest(score_func=chi2)
model.fit(x,y)
model.scores_


/usr/local/lib/python3.10/dist-packages/sklearn/feature_selection/_univariate_selection.py:776: UserWarning: k=10 is greater than n_features=7. All the features will be returned.
  warnings.warn(


array([1411.88704064,   17.60537322,   53.10803984, 2175.56527292,
        127.66934333,    5.39268155,  181.30368904])

**model validation**

this method when we have large data more than data in thousands

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
dataframe
x=dataframe.iloc[:,0:7]
y=dataframe.iloc[:,7]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
model=LogisticRegression()
model.fit(x_train,y_train)
ypred=model.predict(x_test)
model.score(x_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8008658008658008

In [38]:
model.score(x_train,y_train)

0.7690875232774674

2.Evaluate using cross validation


this method when data is in thousands

In [51]:
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename=read_csv('/content/pima-indians-diabetes.data.csv',names=names)
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','classe']
x=filename.drop(labels=['classe'],axis=1)
y=filename.classe
seed=7
kfold=KFold(n_splits=5)
model=LogisticRegression(max_iter=400)
results=cross_val_score(model,x,y,cv=kfold)
results

array([0.79220779, 0.72727273, 0.75324675, 0.81699346, 0.76470588])

3.Evaluate using leave one out cross validation

In [49]:
#this methods when data is in 100's
from pandas import read_csv
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename=read_csv('/content/pima-indians-diabetes.data.csv',names=names)
names = ['preg', 'plas','pres', 'skin','rest','pedi','age','classe']
x=filename.drop(labels=['classe'],axis=1)
y=filename.classe
locv=LeaveOneOut()
model=LogisticRegression(max_iter=300)
results=cross_val_score(model,x,y,cv=locv)


In [50]:
results

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.